from config import PaginationConfig

INVALID_DATE_SELECTION = "INVALID_DATE_SELECTION"
CONFERENCE_WITH_SAME_TITLE_EXIST = "CONFERENCE_WITH_SAME_TITLE_EXIST"
CONFERENCE_NOT_FOUND = "CONFERENCE_NOT_FOUND"
CONFERENCE_INVALID_DATA_PROVIDED = "CONFERENCE_INVALID_DATA_PROVIDED"
TALK_WITH_SAME_TITLE_EXIST = "TALK_WITH_SAME_TITLE_EXIST"
TALK_NOT_FOUND = "TALK_NOT_FOUND"
TALK_INVALID_DATA_PROVIDED = "TALK_INVALID_DATA_PROVIDED"

MAX_PAGE_LIMIT = PaginationConfig.MAX_PAGE_LIMIT
DEFAULT_LIMIT = PaginationConfig.DEFAULT_LIMIT

