"""empty message

Revision ID: 5a1d1d69e57d
Revises: None
Create Date: 2021-11-04 10:27:49.268345

"""

# revision identifiers, used by Alembic.
revision = '5a1d1d69e57d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('speaker', 'participant'), nullable=False),
    sa.Column('for_speaker_talk_id', sa.String(length=32), nullable=True),
    sa.Column('for_participant_talk_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['for_participant_talk_id'], ['talks.id'], ),
    sa.ForeignKeyConstraint(['for_speaker_talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    # ### end Alembic commands ###